[project]
name = "mcp-x-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=1.3.2",
    "openai>=1.75.0",
    "fastmcp>=2.2.0",
    "python-twitter-v2>=0.9.2",
    "dotenv>=0.9.9",
]
